services:
  reverse-proxy:
    container_name: reverse-proxy
    network_mode: host
    image: caddy:2.8-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile

  db:
    container_name: datamonster-db
    image: postgres:16-alpine3.20
    environment:
      POSTGRES_PASSWORD: Password1
      POSTGRES_USER: app
      POSTGRES_DB: records
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  caddy_config: