version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CONN='postgres://app:Password1@localhost:5432/records?sslmode=disable'
      - KEY=${KEY}
      - MODE=prod
    depends_on:
      - db

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - CLERK_PUBLISHABLE_KEY=${PUBLISHABLE_KEY}
    ports:
      - "80:80"
    environment:
      - VITE_PORT=80
      - VITE_CLERK_PUBLISHABLE_KEY=${PUBLISHABLE_KEY}
    depends_on:
      - api

  db:
    image: postgres:16-alpine3.20
    environment:
      POSTGRES_PASSWORD: 'Password1'
      POSTGRES_USER: 'app'
      POSTGRES_DB: 'records'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: