services:
  dm-web:
    container_name: dm-web
    build: ./web
    depends_on:
      - dm-api
    networks:
      - dm-network

  dm-api:
    container_name: dm-api
    build: ./api
    depends_on:
      - dm-records
    networks:
      - dm-network

  dm-records:
    container_name: dm-records
    image: postgres:16
    environment:
      POSTGRES_DB: records
      POSTGRES_USER: app
      POSTGRES_PASSWORD: Password1
    networks:
      - dm-network

networks:
  dm-network:
    name: dm-network  
    driver: bridge
