name: Create AKS Cluster

on:
  workflow_dispatch:

jobs:
  create_aks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy AKS cluster using Bicep
        run: |
          az deployment group create \
            --resource-group datamonster \
            --template-file k8s.bicep \
            --parameters location='westus3' aksClusterName='dm-cluster' kubernetesVersion='1.24.6' dnsPrefix='dmc'
