name: Build and Publish API Docker Image

on:
  push:
    branches:
      - main # Replace with your default branch if different
    paths:
      - "api/**" # Trigger only when changes are merged to the api directory
  workflow_dispatch: # Allows the workflow to be manually triggered

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./api
          file: ./api/Dockerfile # Update the path to your API Dockerfile if needed
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-api:latest
          build-args: |
            AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
            AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
            AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}
            VAULT_URI=${{ secrets.VAULT_URI }}

      - name: Post build info
        run: echo "API Docker image built and pushed to GHCR successfully."
