name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "web/**"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-web:latest

      - name: Post build info
        run: echo "Docker image built and pushed to GHCR successfully."
