name: deploy datamonster-web

on:
  push:
    branches:
      - main
    paths:
      - "web/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io/
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and publish datamonster-web
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/failuretoload/datamonster-web:${{ github.sha }}
          file: ./web/Dockerfile
          build-args: |
            CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "datamonster-web"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_36aabd79f388406489734e57452b5646 }}
          images: "ghcr.io/failuretoload/datamonster-web:${{ github.sha }}"
