name: deploy datamonster-web

on:
  push:
    branches:
      - main
    paths:
      - "web/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DATAMONSTER_ACTIONS }}

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push datamonster-web
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/datamonster-web:latest
          context: ./web
          file: ./web/Dockerfile
          build-args: |
            CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }}