name: Update Azure Web Apps

on:
  push:
    branches:
      - main
    paths:
      - "web/**"
      - "api/**"
  workflow_dispatch:
    inputs:
      deploy_web:
        description: "Deploy Web App"
        required: true
        type: boolean
        default: false
      deploy_api:
        description: "Deploy API App"
        required: true
        type: boolean
        default: false

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest
    outputs:
      WEB_CHANGED: ${{ steps.set-outputs.outputs.WEB_CHANGED }}
      API_CHANGED: ${{ steps.set-outputs.outputs.API_CHANGED }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Determine Changed Files
        if: github.event_name == 'push'
        id: changes
        run: |
          git fetch origin main
          git diff --name-only origin/main...HEAD > changed_files.txt

      - name: Set Outputs for Changed Projects
        id: set-outputs
        run: |
          WEB_CHANGED=false
          API_CHANGED=false
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            WEB_CHANGED=${{ github.event.inputs.deploy_web }}
            API_CHANGED=${{ github.event.inputs.deploy_api }}
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            if grep -q '^web/' changed_files.txt; then WEB_CHANGED=true; fi
            if grep -q '^api/' changed_files.txt; then API_CHANGED=true; fi
          fi
          echo "WEB_CHANGED=${WEB_CHANGED}" >> $GITHUB_OUTPUT
          echo "API_CHANGED=${API_CHANGED}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        if: ${{ steps.set-outputs.outputs.WEB_CHANGED == 'true' || steps.set-outputs.outputs.API_CHANGED == 'true' }}
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        if: ${{ steps.set-outputs.outputs.WEB_CHANGED == 'true' || steps.set-outputs.outputs.API_CHANGED == 'true' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Web Image
        if: ${{ steps.set-outputs.outputs.WEB_CHANGED == 'true' }}
        run: |
          docker build \
            --build-arg CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }} \
            -t ghcr.io/failuretoload/datamonster-web:${{ github.sha }} ./web
          docker push ghcr.io/failuretoload/datamonster-web:${{ github.sha }}

      - name: Build and Push API Image
        if: ${{ steps.set-outputs.outputs.API_CHANGED == 'true' }}
        run: |
          docker build \
            --build-arg AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }} \
            --build-arg AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }} \
            --build-arg AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }} \
            --build-arg VAULT_URI=${{ secrets.VAULT_URI }} \
            -t ghcr.io/failuretoload/datamonster-api:${{ github.sha }} ./api
          docker push ghcr.io/failuretoload/datamonster-api:${{ github.sha }}

  update_azure_web_apps:
    runs-on: ubuntu-latest
    needs: build_and_push_images

    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DATAMONSTER_ACTIONS }}

      - name: Configure datamonster-web
        if: ${{ needs.build_and_push_images.outputs.WEB_CHANGED == 'true' }}
        run: |
          az webapp config appsettings set --name datamonster-web --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --settings DOCKER_REGISTRY_SERVER_URL=https://ghcr.io DOCKER_REGISTRY_SERVER_USERNAME=${{ secrets.GHCR_USERNAME }} DOCKER_REGISTRY_SERVER_PASSWORD=${{ secrets.GHCR_READ }}

      - name: Configure datamonster-api
        if: ${{ needs.build_and_push_images.outputs.WEB_CHANGED == 'true' }}
        run: |
          az webapp config appsettings set --name datamonster-api --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --settings DOCKER_REGISTRY_SERVER_URL=https://ghcr.io DOCKER_REGISTRY_SERVER_USERNAME=${{ secrets.GHCR_USERNAME }} DOCKER_REGISTRY_SERVER_PASSWORD=${{ secrets.GHCR_READ }}

      - name: Update datamonster-api
        if: ${{ needs.build_and_push_images.outputs.API_CHANGED == 'true' }}
        uses: azure/webapps-deploy@v2
        with:
          app-name: "datamonster-api"
          images: "ghcr.io/failuretoload/datamonster-api:${{ github.sha }}"

      - name: Update datamonster-web
        if: ${{ needs.build_and_push_images.outputs.WEB_CHANGED == 'true' }}
        uses: azure/webapps-deploy@v2
        with:
          app-name: "datamonster-web"
          images: "ghcr.io/failuretoload/datamonster-web:${{ github.sha }}"
